# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5551bf42299d1355f34907f98aadd209"
name = "Exp-Mega-Menu"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_app_proxy,write_app_proxy,read_files,write_files,read_metaobjects,write_metaobjects,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_themes,write_themes,unauthenticated_read_product_inventory,unauthenticated_read_product_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
